name: Terraform Scan
run-name: '${{ github.workflow }} | ${{ github.ref_name }}'

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'infrastructure/modules/**'
      - 'infrastructure/stack/**'
      - '.github/workflows/terraform_scan.yml'

jobs:
  terraform-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Scan
        continue-on-error: true
        run: |
          make terraform-scan
